### ISSUE TITLE
如何同时输出在文件和控制台？

### ISSUE THREAD

**Issue by BorgLee** [davyxu/golog#5]

**Comment by davyxu** [comment]
搜索: linux 管道重定向

**Comment by davyxu** [comment]
一般开发流程不输出到文件, 产品上线时, 不输出到命令行只看文件.  两者都要看很影响性能

**Comment by BorgLee** [comment]
OK，我看现在好像是没有按照日期分割的功能的。这个有计划加上么？

**Comment by davyxu** [comment]
golog暂时不维护了, 新的用ulog,  整合logrus的所有功能, 日期分割暂时不考虑, 只按序号备份

**Comment by BorgLee** [comment]
谢谢徐老师。
